#!/usr/bin/env python3
"""
[Codex] Offline Smart Search Backend Engine for Canvas Course Offline Web App.
Provides:
1. SQLite FTS5 incremental indexing of course files (PDFs, PPTXs, text files).
2. Curriculum Topic & Chapter Knowledge Engine mapping syllabus, announcements, and modules to topics/chapters.
3. Multi-tier search API returning curriculum intelligence and ranked document matches.
"""

import os
import re
import json
import sqlite3
import subprocess
import hashlib
import html
import threading
import time
from contextlib import contextmanager
from concurrent.futures import ThreadPoolExecutor
try:
    from .cache import ensure_private_directory, validate_cache_database
    from .archive import walk_files, safe_path, load_blueprint, signature
    from .extraction import extract, SUPPORTED
    from .ocr import capability as ocr_capability, cache_version as ocr_cache_version, retry_failed as retry_failed_ocr
except ImportError:
    from cache import ensure_private_directory, validate_cache_database
    from archive import walk_files, safe_path, load_blueprint, signature
    from extraction import extract, SUPPORTED
    from ocr import capability as ocr_capability, cache_version as ocr_cache_version, retry_failed as retry_failed_ocr

_INDEX_POOL = ThreadPoolExecutor(max_workers=2, thread_name_prefix="canvas-index")
_INDEX_SLOTS = threading.BoundedSemaphore(8)
_STOP_INDEXING = threading.Event()
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple


def get_course_slug(course_name: str) -> str:
    """Generate a clean filesystem-safe slug for a course name."""
    slug = re.sub(r'[^a-zA-Z0-9_-]+', '_', course_name.strip()).strip('_')
    return slug.lower() or "default"


def is_synthetic_file(filename: str, relative_path: str = "") -> bool:
    """Determines whether a file is a synthetic meta-artifact generated by scraper/exporter."""
    fn_low = filename.lower()
    rel_low = relative_path.lower()
    if "/announcements/" in rel_low or rel_low.startswith("announcements/") or "syllabus and admin/announcements" in rel_low:
        if fn_low.endswith((".md", ".txt")):
            return True
    if re.match(r'^\d{4}-\d{2}-\d{2}\s*-\s*', filename) and fn_low.endswith((".md", ".txt")):
        return True
    synthetic_patterns = [
        "course_knowledge.md",
        "assignments_and_milestones_timeline.md",
        "announcements_assigned_homework.md",
        "lecture_video_recordings.md",
        "external_web_links.md",
    ]
    for pattern in synthetic_patterns:
        if pattern in fn_low:
            return True
    return False


def query_parts(query):
    """Treat FTS operators as text, preserving explicit quoted phrases."""
    parts = []
    for phrase, word in re.findall(r'"([^"\n]+)"|(\w+)', query[:512], re.UNICODE):
        tokens = re.findall(r'\w+', phrase or word, re.UNICODE)
        if tokens:
            parts.append('"' + ' '.join(tokens) + '"' + ('' if phrase else '*'))
    return parts[:32]


def highlight_terms(text, query, max_chars=180):
    text = (text or '')[:max_chars]
    words = re.findall(r'\w+', query[:512], re.UNICODE)[:32]
    if not words:
        return html.escape(text)
    pattern = re.compile('|'.join(re.escape(w) for w in sorted(set(words), key=len, reverse=True)), re.I)
    pieces, start = [], 0
    for match in pattern.finditer(text):
        pieces.extend((html.escape(text[start:match.start()]), '<mark>', html.escape(match[0]), '</mark>'))
        start = match.end()
    return ''.join(pieces) + html.escape(text[start:])


class CurriculumKnowledgeEngine:
    """
    Curriculum Topic & Chapter Knowledge Engine.
    Parses canvas_course.json modules, syllabus documents, and announcements
    to map course concepts to Chapters and Modules.
    """

    def __init__(self, course_path: Path, course_name: str, blueprint: Optional[Dict[str, Any]] = None, file_map=None):
        self.course_path = course_path
        self.course_name = course_name
        self.blueprint = blueprint or {}
        self.file_map = self._build_disk_file_map() if file_map is None else file_map
        self.knowledge_base = self._build_knowledge_base()

    def _build_disk_file_map(self) -> Dict[str, str]:
        """Maps filename to relative path in course directory."""
        res = {}
        for path, relative, _ in walk_files(self.course_path):
            if path.name != 'canvas_course.json':
                res.setdefault(path.name.lower(), relative)
        for key, value in self.blueprint.get('file_path_map', {}).items():
            try:
                target = safe_path(self.course_path, value)
                res[str(key).lower()] = target.relative_to(self.course_path).as_posix()
            except (ValueError, OSError, TypeError):
                continue
        return res

    def resolve_file(self, filename: str) -> Optional[Dict[str, str]]:
        """Resolve a filename to its relative path."""
        fn_low = filename.lower()
        if fn_low in self.file_map:
            return {"name": filename, "path": self.file_map[fn_low]}
        # Try finding suffix or stem match
        for k, v in self.file_map.items():
            if fn_low == k or fn_low in k or Path(k).name == fn_low:
                return {"name": Path(v).name, "path": v}
        return None

    def _build_knowledge_base(self) -> List[Dict[str, Any]]:
        """Synthesizes structured topic/chapter knowledge from syllabus, announcements, and modules."""
        topics = []
        # 1. Dynamic Module Ingestion from course blueprint
        if self.blueprint and "modules" in self.blueprint:
            for mod in self.blueprint.get("modules", []):
                mod_title = mod.get("name") or mod.get("title") or ""
                if not mod_title or mod_title.lower() == "general materials":
                    continue

                mod_items = [it.get("title") for it in mod.get("items", []) if it.get("title")]
                mod_files = []
                for item_title in mod_items:
                    res = self.resolve_file(item_title)
                    if res and not is_synthetic_file(res["name"], res["path"]):
                        mod_files.append(item_title)

                # Extract keywords from module title
                kw_set = set()
                # Whole clean title
                clean_title = re.sub(r'^[A-Z]+\s+\d+[A-Z]?\s*', '', mod_title).strip()
                kw_set.add(clean_title.lower())

                # Chapters or units
                ch_matches = re.findall(r'(?:Chapter[s]?|Ch\.?|Unit[s]?)\s*([\d\s,&and]+)', mod_title, re.IGNORECASE)
                ch_label = ""
                if ch_matches:
                    ch_str = ch_matches[0].strip()
                    ch_label = f"Chapter {ch_str}"
                    for num in re.findall(r'\d+', ch_str):
                        kw_set.add(f"chapter {num}")
                        kw_set.add(f"ch {num}")
                        kw_set.add(f"ch{num}")

                # Exam / Midterm / Final keywords
                if re.search(r'\b(?:midterm|exam|final|quiz)\b', mod_title, re.IGNORECASE):
                    for word in ["midterm", "exam", "final", "quiz", "practice exam"]:
                        if word in mod_title.lower():
                            kw_set.add(word)

                # Topic tokens (>3 letters, non-stopword)
                tokens = [w.lower() for w in re.findall(r'[a-zA-Z]{3,}', mod_title)]
                stopwords = {'and', 'the', 'for', 'with', 'materials', 'slides', 'presentation', 'presentations', 'resources', 'lectures', 'lecture', 'discussion', 'discussions'}
                for t in tokens:
                    if t not in stopwords:
                        kw_set.add(t)

                topics.append({
                    "keywords": sorted(list(kw_set)),
                    "chapter": ch_label or clean_title,
                    "module_title": mod_title,
                    "topic": clean_title,
                    "reason": "Identified from Course Blueprint Modules",
                    "target_files": mod_files[:8]
                })

        # 2. Dynamic Syllabus Schedule Ingestion
        if self.blueprint and "syllabus" in self.blueprint:
            syl = self.blueprint.get("syllabus", {})
            schedule = syl.get("structured", {}).get("schedule", [])
            for item in schedule:
                title = item.get("title", "")
                if not title or len(title) < 4:
                    continue
                matched_file = item.get("file_name")
                kw_set = {title.lower()}
                for t in re.findall(r'[a-zA-Z]{4,}', title):
                    if t.lower() not in {'assignment', 'event', 'calendar', 'lecture', 'quiz'}:
                        kw_set.add(t.lower())

                topics.append({
                    "keywords": sorted(list(kw_set)),
                    "chapter": item.get("date", "Syllabus Schedule"),
                    "module_title": "Syllabus Schedule",
                    "topic": title,
                    "reason": "Identified from Syllabus Course Schedule",
                    "target_files": [matched_file] if matched_file else []
                })

        return topics

    def match_curriculum(self, query: str) -> List[Dict[str, Any]]:
        """Match query against curriculum knowledge base."""
        q_low = query.lower().strip()
        q_tokens = set(re.findall(r'[a-zA-Z0-9]+', q_low))
        matches = []
        seen_chapters = set()

        for item in self.knowledge_base:
            matched = False
            # Check exact keyword or token overlap
            for kw in item["keywords"]:
                if kw and (re.search(r'(?<!\w)' + re.escape(kw) + r'(?!\w)', q_low) or re.search(r'(?<!\w)' + re.escape(q_low) + r'(?!\w)', kw)):
                    matched = True
                    break
                kw_tokens = set(re.findall(r'[a-zA-Z0-9]+', kw))
                if kw_tokens and kw_tokens.issubset(q_tokens):
                    matched = True
                    break

            query_numbers = set(re.findall(r'\d+', q_low))
            item_numbers = set(re.findall(r'\d+', item['chapter'] + ' ' + item['module_title']))
            if query_numbers and not query_numbers.issubset(item_numbers):
                matched = False
            if matched:
                chapter_key = (item["chapter"], item["module_title"])
                if chapter_key in seen_chapters:
                    continue
                seen_chapters.add(chapter_key)

                # Resolve associated files
                resolved_files = []
                for target_fn in item.get("target_files", []):
                    res = self.resolve_file(target_fn)
                    if res:
                        resolved_files.append(res)

                matches.append({
                    "chapter": item["chapter"],
                    "module_title": item["module_title"],
                    "topic": item["topic"],
                    "reason": item["reason"],
                    "associated_files": resolved_files
                })

        return matches


class SearchEngine:
    """
    Incremental Search Engine for an offline Canvas Course.
    Uses SQLite FTS5 for fast full-text search and CurriculumKnowledgeEngine
    for curriculum-level topic and chapter intelligence.
    """

    def __init__(self, course_name: str, course_path: str | Path, cache_dir=None):
        self.course_name = course_name
        self.course_path = Path(course_path).resolve()
        self.course_slug = get_course_slug(course_name)
        self.cache_dir = Path(cache_dir or os.environ.get('CANVAS_CACHE_DIR', Path.home() / '.canvas_search_cache'))
        ensure_private_directory(self.cache_dir)
        identity = hashlib.sha256(str(self.course_path).encode()).hexdigest()[:20]
        self.db_path = self.cache_dir / f'{self.course_slug[:60]}-{identity}-v2.db'
        self._lock = threading.RLock()
        self._job_lock = threading.Lock()
        self._future = None
        self._pending_force = False
        self._last_check = 0
        self._status = dict(state='idle', processed=0, total=0, failed=0, last_error=None)
        self._worker_active = False
        self.blueprint = {}
        self.curriculum_engine = CurriculumKnowledgeEngine(self.course_path, course_name, {}, file_map={})
        self._init_db()
        with self._get_connection() as conn:
            self._refresh_status(conn)

    @contextmanager
    def _get_connection(self, bounded=False):
        validate_cache_database(self.db_path)
        conn = sqlite3.connect(str(self.db_path), timeout=5)
        conn.row_factory = sqlite3.Row
        deadline = time.monotonic() + 3
        if bounded:
            conn.set_progress_handler(lambda: int(time.monotonic() > deadline), 10000)
        try:
            with conn:
                yield conn
        finally:
            conn.close()

    def _init_db(self):
        with self._get_connection() as conn:
            conn.execute('PRAGMA journal_mode=WAL')
            conn.execute('CREATE TABLE IF NOT EXISTS indexed_files (file_path TEXT PRIMARY KEY, mtime INTEGER, size INTEGER, fingerprint TEXT, digest TEXT, filename TEXT, error TEXT)')
            conn.execute("CREATE VIRTUAL TABLE IF NOT EXISTS doc_pages_fts USING fts5(file_path UNINDEXED, filename, folder, page_num UNINDEXED, content, tokenize='porter unicode61')")
            conn.execute('CREATE TABLE IF NOT EXISTS page_ids (file_path TEXT, row_id INTEGER PRIMARY KEY)')
            conn.execute('CREATE INDEX IF NOT EXISTS page_paths ON page_ids(file_path)')
            columns = {r[1] for r in conn.execute('PRAGMA table_info(indexed_files)')}
            for name, declaration in [('ocr', "TEXT DEFAULT '{}'"), ('retry_at', 'REAL DEFAULT 0'), ('attempts', 'INTEGER DEFAULT 0')]:
                if name not in columns:
                    conn.execute(f'ALTER TABLE indexed_files ADD COLUMN {name} {declaration}')
            conn.execute('CREATE TABLE IF NOT EXISTS index_meta (key TEXT PRIMARY KEY, value TEXT)')
            conn.execute("INSERT OR IGNORE INTO index_meta VALUES ('revision', '0')")

    def _revision(self, conn):
        conn.execute("UPDATE index_meta SET value=CAST(value AS INTEGER)+1 WHERE key='revision'")
        return int(conn.execute("SELECT value FROM index_meta WHERE key='revision'").fetchone()[0])

    def _refresh_status(self, conn):
        records = conn.execute('SELECT ocr, error, retry_at FROM indexed_files').fetchall()
        progress = [json.loads(row['ocr'] or '{}') for row in records]
        pending = sum(p.get('pending', 0) for p in progress)
        revision = int(conn.execute("SELECT value FROM index_meta WHERE key='revision'").fetchone()[0])
        with self._job_lock:
            self._status.update(revision=revision, indexed_files=len(records),
                                pending_ocr=pending, partial=bool(pending or any(r['retry_at'] for r in records)),
                                ocr_total=sum(p.get('total', 0) for p in progress),
                                ocr_completed=sum(p.get('completed', 0) for p in progress),
                                ocr_failed=sum(p.get('failed', 0) for p in progress),
                                failed=sum(bool(r['error']) for r in records))

    def status(self):
        with self._job_lock:
            total = self._status.get('total', 0) + self._status.get('ocr_total', 0)
            done = self._status.get('processed', 0) + self._status.get('ocr_completed', 0) + self._status.get('ocr_failed', 0)
            percentage = round(min(100, 100 * done / total), 1) if total else (100 if self._status['state'] == 'ready' else 0)
            phase = self._status.get('phase', 'idle')
            if self._status['state'] == 'ready' and self._status.get('pending_ocr'):
                phase = 'ocr'
            elif self._status.get('state') == 'ready' and not self._status.get('pending_ocr'):
                percentage = 100.0
                phase = 'idle'
            return dict(self._status, phase=phase, percent_complete=percentage, ocr=ocr_capability())

    def request_index(self, force=False):
        with self._job_lock:
            if self._worker_active:
                if force:
                    self._pending_force = True
                    self._status['rebuild_pending'] = True
                return dict(self._status)
            if not force and time.monotonic() - self._last_check < 5:
                return dict(self._status)
            if not _INDEX_SLOTS.acquire(blocking=False):
                self._status['deferred'] = True
                return dict(self._status)
            self._status.update(state='queued', phase='scanning', processed=0, last_error=None, deferred=False)
            self._worker_active = True
            try:
                self._future = _INDEX_POOL.submit(self._background_index, force)
            except Exception:
                self._worker_active = False
                _INDEX_SLOTS.release()
                raise
            return dict(self._status)

    def _background_index(self, force):
        try:
            while True:
                self.index_course(force)
                with self._job_lock:
                    if not self._pending_force or _STOP_INDEXING.is_set():
                        self._worker_active = False
                        return
                    self._pending_force = False
                    self._status['rebuild_pending'] = False
                    force = True
        except Exception as exc:
            with self._job_lock:
                self._worker_active = False
                self._status.update(state='error', last_error=type(exc).__name__)
        finally:
            _INDEX_SLOTS.release()

    def index_course(self, force=False):
        with self._lock:
            with self._job_lock:
                self._status.update(state='indexing', phase='scanning', processed=0, current_file=None)
            inventory = [(p, rel, sig) for p, rel, sig in walk_files(self.course_path)
                         if p.suffix.lower() in SUPPORTED and not is_synthetic_file(p.name, rel)]
            with self._job_lock:
                self._status.update(total=len(inventory), phase='extracting')
            bp_path = self.course_path / 'canvas_course.json'
            if not bp_path.is_file():
                for cand in (
                    self.course_path / f"{self.course_path.name} Lectures & Resources" / 'canvas_course.json',
                    self.course_path / f"{self.course_name} Lectures & Resources" / 'canvas_course.json',
                    self.course_path / 'Lectures' / 'canvas_course.json',
                ):
                    if cand.is_file():
                        bp_path = cand
                        break
            if not bp_path.is_file():
                try:
                    for sub in self.course_path.iterdir():
                        if sub.is_dir() and not sub.is_symlink():
                            if (sub / 'canvas_course.json').is_file():
                                bp_path = sub / 'canvas_course.json'
                                break
                            try:
                                for sub2 in sub.iterdir():
                                    if sub2.is_dir() and not sub2.is_symlink() and (sub2 / 'canvas_course.json').is_file():
                                        bp_path = sub2 / 'canvas_course.json'
                                        break
                            except OSError:
                                pass
                            if bp_path.is_file():
                                break
                except OSError:
                    pass

            blueprint = {}
            try:
                if bp_path.is_file():
                    blueprint = load_blueprint(bp_path)
            except (OSError, ValueError, TypeError, AttributeError):
                blueprint = {}
            curriculum = CurriculumKnowledgeEngine(self.course_path, self.course_name, blueprint)
            indexed = skipped = 0
            with self._get_connection() as conn:
                old = {r['file_path']: dict(r) for r in conn.execute('SELECT * FROM indexed_files')}
                # Forced passes replace rows inside one transaction; retaining old
                # rows until each file succeeds permits safe transient-error fallback.
                for position, (path, relative, sig) in enumerate(inventory, 1):
                    if _STOP_INDEXING.is_set():
                        raise RuntimeError('Indexing stopped')
                    fingerprint = json.dumps(sig)
                    if path.suffix.lower() == '.pdf':
                        fingerprint += ':' + ocr_cache_version()
                    previous = old.get(relative, {})
                    prior_ocr = json.loads(previous.get('ocr') or '{}')
                    same = previous.get('fingerprint') == fingerprint
                    retry_due = previous.get('retry_at', 0) and previous['retry_at'] <= time.time()
                    ocr_due = prior_ocr.get('pending', 0) and prior_ocr.get('retry_at', 0) <= time.time()
                    if not force and same and not retry_due and not ocr_due:
                        skipped += 1
                    else:
                        with self._job_lock:
                            self._status.update(current_file=relative)
                        pages, error, progress, retry_at = [], None, {}, 0
                        attempts = previous.get('attempts', 0) if same and not force else 0
                        digest = relative
                        replace_pages = True
                        try:
                            safe_path(self.course_path, relative)
                            if force and path.suffix.lower() == '.pdf':
                                retry_failed_ocr(path)
                            pages = extract(path)
                            error = getattr(pages, 'warning', None)
                            progress = getattr(pages, 'ocr', {})
                            file_digest = hashlib.sha256()
                            with path.open('rb') as source:
                                for chunk in iter(lambda: source.read(1024 * 1024), b''):
                                    file_digest.update(chunk)
                            if signature(path) != sig:
                                raise OSError('File changed during extraction')
                            if any(t.strip() for _, t in pages):
                                digest = file_digest.hexdigest()
                            attempts = 0
                        except Exception as exc:
                            pages, progress = [], {}
                            error = type(exc).__name__
                            attempts += 1
                            if isinstance(exc, (OSError, subprocess.SubprocessError)) and attempts < 3:
                                retry_at = time.time() + 30 * 2 ** (attempts - 1)
                            if same:
                                replace_pages = False
                                digest = previous['digest']
                                progress = dict(prior_ocr)
                                if retry_at:
                                    progress['retry_at'] = retry_at
                                elif progress.get('pending'):
                                    progress['failed'] = progress.get('failed', 0) + progress.pop('pending')
                        if replace_pages:
                            conn.execute('DELETE FROM doc_pages_fts WHERE rowid IN (SELECT row_id FROM page_ids WHERE file_path=?)', (relative,))
                            conn.execute('DELETE FROM page_ids WHERE file_path=?', (relative,))
                            for number, text in pages:
                                text = text.replace('\x01', '').replace('\x02', '')
                                if text.strip():
                                    cursor = conn.execute('INSERT INTO doc_pages_fts VALUES (?, ?, ?, ?, ?)',
                                                          (relative, path.name, str(Path(relative).parent), number, text))
                                    conn.execute('INSERT INTO page_ids VALUES (?, ?)', (relative, cursor.lastrowid))
                        conn.execute('INSERT OR REPLACE INTO indexed_files (file_path, mtime, size, fingerprint, digest, filename, error, ocr, retry_at, attempts) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                                     (relative, sig[0], sig[2], fingerprint, digest, path.name, error, json.dumps(progress), retry_at, attempts))
                        indexed += 1
                        if not force:
                            revision = self._revision(conn)
                            conn.commit()  # Make completed files searchable during a long first pass.
                            with self._job_lock:
                                self._status['revision'] = revision
                                for key, field in [('pending_ocr', 'pending'), ('ocr_total', 'total'), ('ocr_completed', 'completed'), ('ocr_failed', 'failed')]:
                                    self._status[key] = self._status.get(key, 0) + progress.get(field, 0) - prior_ocr.get(field, 0)
                                self._status['failed'] = self._status.get('failed', 0) + bool(error) - bool(previous.get('error'))
                                self._status['partial'] = bool(self._status['pending_ocr'] or retry_at)
                                self._status['indexed_files'] = self._status.get('indexed_files', 0) + int(not previous)
                    with self._job_lock:
                        self._status.update(processed=position)
                removed_paths = old.keys() - {rel for _, rel, _ in inventory}
                for removed in removed_paths:
                    conn.execute('DELETE FROM doc_pages_fts WHERE rowid IN (SELECT row_id FROM page_ids WHERE file_path=?)', (removed,))
                    conn.execute('DELETE FROM page_ids WHERE file_path=?', (removed,))
                    conn.execute('DELETE FROM indexed_files WHERE file_path=?', (removed,))
                curriculum_signature = hashlib.sha256(json.dumps(blueprint, sort_keys=True).encode()).hexdigest()
                old_signature = conn.execute("SELECT value FROM index_meta WHERE key='curriculum'").fetchone()
                if force or removed_paths or not old_signature or old_signature[0] != curriculum_signature:
                    self._revision(conn)
                conn.execute("INSERT OR REPLACE INTO index_meta VALUES ('curriculum', ?)", (curriculum_signature,))
                conn.commit()
                self.blueprint, self.curriculum_engine = blueprint, curriculum
                self._refresh_status(conn)
            self._last_check = time.monotonic()
            with self._job_lock:
                self._status.update(state='ready', phase='idle', current_file=None, indexed=indexed,
                                    skipped=skipped, last_error=None, finished_at=time.time(),
                                    processed=len(inventory))
            return dict(course=self.course_name, indexed=indexed, skipped=skipped, total_active=len(inventory))

    def ensure_indexed(self):
        return self.request_index()

    def search(self, query: str, limit: int = 30) -> Dict[str, Any]:
        """Search the current committed snapshot without blocking indexing."""
        try:
            from .search_quality import search
        except ImportError:
            from search_quality import search
        return search(self, query, limit)

    def _get_all_indexed_file_paths(self) -> Dict[str, Tuple[float, int]]:
        """Retrieve all currently indexed paths."""
        res = {}
        with self._get_connection() as conn:
            for row in conn.execute("SELECT file_path, mtime, size FROM indexed_files"):
                res[row["file_path"]] = (row["mtime"], row["size"])
        return res


# In-memory search engine instances
_engine_cache: Dict[str, SearchEngine] = {}
_engine_lock = threading.Lock()


def get_search_engine(course_name, course_path):
    key = str(Path(course_path).resolve())
    with _engine_lock:
        if key not in _engine_cache:
            if len(_engine_cache) >= 64:
                for old_key, engine in list(_engine_cache.items()):
                    if not engine._future or engine._future.done():
                        del _engine_cache[old_key]
                        break
            _engine_cache[key] = SearchEngine(course_name, course_path)
        return _engine_cache[key]
