# canvas_blueprint.py
# Captures and builds the complete Canvas Course Blueprint (canvas_course.json)
# for 1:1 offline Canvas LMS recreation, module tree mapping, and chronological timeline.

import os
from pathlib import Path
import re
import json
import time
import stat
import secrets
from contextlib import ExitStack
from safety import contained_path, validate_component
from datetime import datetime
from typing import Dict, List, Any, Optional


def parse_datetime_to_iso(date_str: str) -> Optional[str]:
    """Parses various date/time formats from Canvas into ISO 8601 strings."""
    if not date_str or date_str.lower() in ("not specified", "n/a", "none"):
        return None
    cleaned = date_str.strip()
    
    current_year = datetime.now().year
    # Try formats with year
    for fmt in [
        "%Y-%m-%dT%H:%M:%S%z",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d",
        "%b %d, %Y at %I:%M%p",
        "%b %d, %Y at %I:%M %p",
        "%B %d, %Y at %I:%M%p",
        "%B %d, %Y at %I:%M %p",
        "%B %d, %Y",
        "%b %d, %Y",
        "%m/%d/%Y %I:%M %p",
        "%m/%d/%Y %H:%M",
        "%m/%d/%Y",
    ]:
        try:
            dt = datetime.strptime(cleaned, fmt)
            return dt.isoformat()
        except Exception:
            continue

    # Try formats without year by prepending current year
    for fmt in [
        "%Y %b %d at %I:%M%p",
        "%Y %b %d at %I:%M %p",
        "%Y %B %d at %I:%M%p",
        "%Y %B %d at %I:%M %p",
        "%Y %b %d",
        "%Y %B %d",
    ]:
        try:
            dt = datetime.strptime(f"{current_year} {cleaned}", fmt)
            return dt.isoformat()
        except Exception:
            continue

    return cleaned


def format_datetime_for_display(dt_str: str) -> str:
    """Formats an ISO or raw datetime string into a clean, human-readable date/time."""
    if not dt_str or str(dt_str).strip() in ("—", "None", "", "not specified"):
        return "—"
    clean = re.sub(r'^\s*Due\s*', '', str(dt_str).strip(), flags=re.IGNORECASE)
    parts = [p.strip() for p in clean.split("\n") if p.strip()]
    if parts:
        clean = parts[0]
    try:
        if "T" in clean:
            clean_iso = clean.replace("Z", "+00:00")
            dt = datetime.fromisoformat(clean_iso)
            return dt.strftime("%b %d, %Y at %I:%M %p")
    except Exception:
        pass
def is_synthetic_file(filename: str, relative_path: str = "") -> bool:
    """Determines whether a file is a synthetic meta-artifact generated by the scraper/exporter,
    rather than an original instructor course document."""
    fn_low = filename.lower()
    rel_low = relative_path.lower()

    # 1. Individual announcement exports (.md, .txt)
    if "/announcements/" in rel_low or rel_low.startswith("announcements/") or "syllabus and admin/announcements" in rel_low:
        if fn_low.endswith((".md", ".txt")):
            return True
    if re.match(r'^\d{4}-\d{2}-\d{2}\s*-\s*', filename) and fn_low.endswith((".md", ".txt")):
        return True

    # 2. Synthetic summaries, curriculum digests, and timeline reports
    synthetic_patterns = [
        "course_knowledge.md",
        "assignments_and_milestones_timeline.md",
        "announcements_assigned_homework.md",
        "lecture_video_recordings.md",
        "external_web_links.md",
    ]
    for pattern in synthetic_patterns:
        if pattern in fn_low:
            return True

    return False


class CourseBlueprint:
    """Manages the full structural representation of a Canvas course."""

    def __init__(self, course_name: str, course_url: str, output_dir: str):
        self.course_name = course_name
        self.course_url = course_url
        self.output_dir = output_dir
        self.scraped_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        self.tabs: List[Dict[str, Any]] = []
        self.modules: List[Dict[str, Any]] = []
        self.announcements: List[Dict[str, Any]] = []
        self.assignments: List[Dict[str, Any]] = []
        self.discussions: List[Dict[str, Any]] = []
        self.quizzes: List[Dict[str, Any]] = []
        self.syllabus: Dict[str, Any] = {}
        self.grades: Dict[str, Any] = {}
        self.media_recordings: List[Dict[str, Any]] = []
        self.external_links: List[Dict[str, Any]] = []
        self.timeline: List[Dict[str, Any]] = []
        self.file_path_map: Dict[str, str] = {}  # filename -> relative disk path

    def set_tabs(self, tabs: List[Dict[str, Any]]):
        self.tabs = tabs

    def add_module(self, module_id: str, title: str, items: List[Dict[str, Any]]):
        self.modules.append({
            "id": module_id or f"mod_{len(self.modules) + 1}",
            "title": title,
            "items": items
        })

    def add_announcement(self, ann_data: Dict[str, Any]):
        self.announcements.append(ann_data)

    def add_assignment(self, assign_data: Dict[str, Any]):
        self.assignments.append(assign_data)

    def add_discussion(self, disc_data: Dict[str, Any]):
        self.discussions.append(disc_data)

    def add_quiz(self, quiz_data: Dict[str, Any]):
        self.quizzes.append(quiz_data)

    def set_syllabus(self, syl_data: Dict[str, Any]):
        self.syllabus = syl_data

    def set_grades(self, grades_data: Dict[str, Any]):
        self.grades = grades_data

    def register_file_placement(self, filename: str, relative_path: str):
        """Maps a filename to its organized relative path on disk (ignoring synthetic meta-files)."""
        relative_path = relative_path.replace('\\', '/') if os.name == 'nt' else relative_path
        if is_synthetic_file(filename, relative_path):
            return
        self.file_path_map[filename] = relative_path

    def compile_timeline(self):
        """Compiles all assignments, announcements, quizzes, and discussion posts into a unified chronological timeline."""
        events = []

        # 1. Assignments
        for a in self.assignments:
            events.append({
                "id": a.get("id") or f"assign_{len(events)}",
                "type": "assignment",
                "title": a.get("title", "Untitled Assignment"),
                "date_assigned": a.get("available_from") or a.get("date_assigned") or a.get("created_at"),
                "date_due": a.get("due_date") or a.get("due"),
                "date_until": a.get("until"),
                "points": a.get("points"),
                "group": a.get("group", "Assignments"),
                "submission_status": a.get("submission_status", "unsubmitted"),
                "submitted_at": a.get("submitted_at"),
                "score": a.get("score"),
                "details": a.get("description", "")[:500],
                "local_file": a.get("local_file") or self.file_path_map.get(a.get("title")),
                "url": a.get("url")
            })

        # 2. Announcements
        for ann in self.announcements:
            events.append({
                "id": ann.get("id") or f"ann_{len(events)}",
                "type": "announcement",
                "title": ann.get("title", "Course Announcement"),
                "date_assigned": ann.get("posted_at") or ann.get("date"),
                "date_due": None,
                "author": ann.get("author", "Instructor"),
                "details": ann.get("body", "")[:500],
                "homework_extracted": ann.get("homework_extracted", []),
                "local_file": ann.get("local_file"),
                "url": ann.get("url")
            })

        # 3. Quizzes
        for q in self.quizzes:
            events.append({
                "id": q.get("id") or f"quiz_{len(events)}",
                "type": "quiz",
                "title": q.get("title", "Course Quiz"),
                "date_assigned": q.get("available_from"),
                "date_due": q.get("due_date") or q.get("due"),
                "points": q.get("points"),
                "submission_status": q.get("submission_status", "unsubmitted"),
                "details": q.get("details", "")[:500],
                "local_file": q.get("local_file") or self.file_path_map.get(q.get("title")),
                "url": q.get("url")
            })

        # Sort events chronologically (using due date or assigned date)
        def sort_key(e):
            dt = e.get("date_due") or e.get("date_assigned") or "9999"
            return str(dt)

        events.sort(key=sort_key)
        self.timeline = events

    @classmethod
    def load(cls, filepath: str) -> "CourseBlueprint":
        """Loads an existing CourseBlueprint from canvas_course.json."""
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        bp = cls(
            course_name=data.get("course_name", ""),
            course_url=data.get("course_url", ""),
            output_dir=os.path.dirname(filepath)
        )
        bp.scraped_at = data.get("scraped_at", bp.scraped_at)
        bp.tabs = data.get("tabs", [])
        bp.modules = data.get("modules", [])
        bp.announcements = data.get("announcements", [])
        bp.assignments = data.get("assignments", [])
        bp.discussions = data.get("discussions", [])
        bp.quizzes = data.get("quizzes", [])
        bp.syllabus = data.get("syllabus", {})
        bp.grades = data.get("grades", {})
        bp.media_recordings = data.get("media_recordings", [])
        bp.external_links = data.get("external_links", [])
        bp.timeline = data.get("timeline", [])
        bp.file_path_map = data.get("file_path_map", {})
        bp.clean_announcements()
        bp.link_announcements_to_files()
        return bp

    def scan_course_directory(self, course_root: str):
        """Scans all organized files in the course directory and registers their relative paths."""
        ignore_files = {".ds_store", "canvas_course.json", ".session_cookies.json", ".modules_map.json",
                        ".modules_tree.json", ".file_metadata.json", ".announcements.json"}
        # [Codex] Preserve aliases only for live visible contained files. Never
        # index recovery copies, staging data, or symbolic links.
        base = Path(course_root).resolve()
        def visible_file(relative):
            path = Path(str(relative))
            if path.is_absolute() or any(part.startswith('.') for part in path.parts):
                return False
            target = base / path
            try:
                return (target.is_file() and target.resolve().is_relative_to(base)
                        and not any(p.is_symlink() for p in (target, *target.parents) if p != base and p.is_relative_to(base)))
            except (OSError, ValueError, RuntimeError):
                return False
        self.file_path_map = {
            fname: rpath for fname, rpath in self.file_path_map.items()
            if not is_synthetic_file(fname, rpath) and visible_file(rpath)
        }
        for root, dirs, files in os.walk(course_root):
            dirs[:] = [d for d in dirs if not d.startswith('.') and not (Path(root) / d).is_symlink()]
            for f in files:
                if f.lower() in ignore_files or f.startswith("."):
                    continue
                abs_path = os.path.join(root, f)
                rel_path = os.path.relpath(abs_path, course_root)
                if visible_file(rel_path) and not is_synthetic_file(f, rel_path):
                    self.register_file_placement(f, rel_path)

        self.link_syllabus_files()
        self.clean_announcements()
        self.link_announcements_to_files()
        self.link_gradescope_assignments()
        self.compile_timeline()

    def link_syllabus_files(self):
        """Scans for official syllabus PDFs and visual snapshots to link them to the syllabus blueprint."""
        if not self.syllabus:
            self.syllabus = {}

        pdf_file = None
        pdf_path = None
        snapshot_pdf = None
        snapshot_path = None

        for fname, rpath in self.file_path_map.items():
            fn_low = fname.lower()
            if fn_low.endswith(".pdf"):
                if "visual_snapshot" in fn_low or "snapshot" in fn_low:
                    snapshot_pdf = fname
                    snapshot_path = rpath
                elif "syllabus" in fn_low and not pdf_file:
                    pdf_file = fname
                    pdf_path = rpath

        if pdf_file:
            self.syllabus["has_pdf"] = True
            self.syllabus["pdf_file"] = pdf_file
            self.syllabus["pdf_path"] = pdf_path
        else:
            self.syllabus["has_pdf"] = False

        if snapshot_pdf:
            self.syllabus["snapshot_pdf"] = snapshot_pdf
            self.syllabus["snapshot_path"] = snapshot_path

        self.parse_syllabus_content()

    def parse_syllabus_content(self, course_root: str = None):
        """Extracts structured instructor info, TA directory, Zoom links, and schedule items from the syllabus."""
        if not self.syllabus:
            return

        body = self.syllabus.get("body", "")
        if not body:
            return

        # Find any zoom URIs embedded in PDFs (such as Syllabus_Visual_Snapshot.pdf)
        zoom_urls = {}
        root = course_root or self.output_dir
        if root:
            candidates = []
            if self.syllabus.get("snapshot_path"):
                candidates.append(os.path.join(root, self.syllabus["snapshot_path"]))
            if self.syllabus.get("pdf_path"):
                candidates.append(os.path.join(root, self.syllabus["pdf_path"]))

            try:
                import pypdf
                from urllib.parse import unquote
                for pdf_abs in candidates:
                    if os.path.exists(pdf_abs):
                        try:
                            reader = pypdf.PdfReader(pdf_abs)
                            for page in reader.pages:
                                if '/Annots' in page:
                                    for a in page['/Annots']:
                                        obj = a.get_object()
                                        if '/A' in obj and '/URI' in obj['/A']:
                                            u = obj['/A']['/URI']
                                            if 'url?q=' in u:
                                                m_q = re.search(r'url\?q=([^&]+)', u)
                                                if m_q:
                                                    u = unquote(m_q.group(1))
                                            if 'zoom.us' in u:
                                                m_id = re.search(r'/j/(\d+)', u)
                                                if m_id:
                                                    zoom_urls[m_id.group(1)] = u
                        except Exception:
                            pass
            except ImportError:
                pass

        # Format Zoom meeting ID helper
        def fmt_mid(raw: str) -> str:
            raw = re.sub(r'\D', '', str(raw or ''))
            if len(raw) == 11:
                return f"{raw[:3]} {raw[3:7]} {raw[7:]}"
            elif len(raw) == 10:
                return f"{raw[:3]} {raw[3:6]} {raw[6:]}"
            return raw

        # Extract Zoom URLs directly from body if present
        for m in re.finditer(r'(https://[a-zA-Z0-9\.\-_]*zoom\.us/[jw]/(\d+)(?:\?[^\s\)\"\'>]+)?)', body):
            zoom_urls[re.sub(r'\D', '', m.group(2))] = m.group(1)

        structured = {}

        # 1. Dynamic Lecture Info & Zoom Link
        lecture_info = {}
        # Search for lecture schedule pattern
        sched_match = re.search(r'((?:Mon|Tue|Wed|Thu|Fri|Sat|Sun|MWF|TTh|TuTh|MW|TR)[\s\w,/-]*\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?\s*(?:-|to)\s*\d{1,2}(?::\d{2})?\s*(?:am|pm|AM|PM)?)', body)
        lecture_sched = sched_match.group(1).strip() if sched_match else ""

        # Search for lecture zoom info
        lec_m = re.search(r'Lecture(?:\s+Zoom\s+Link)?[:\s\n]+.*?(https://[^\s/]*zoom\.us/[jw]/(\d+)[^\s\)\"\']*)', body, re.IGNORECASE | re.DOTALL)
        lec_mid = ""
        lec_zoom = ""
        if lec_m:
            lec_zoom = lec_m.group(1)
            lec_mid = re.sub(r'\D', '', lec_m.group(2))
        else:
            # Check if any zoom url in zoom_urls has meeting ID associated with lecture
            mid_lec_m = re.search(r'(?:Lecture|Class)\s+Meeting\s+ID:?[\s\xa0]*([\d\s]{9,13})', body, re.IGNORECASE)
            if mid_lec_m:
                lec_mid = re.sub(r'\D', '', mid_lec_m.group(1))
                lec_zoom = zoom_urls.get(lec_mid, f"https://zoom.us/j/{lec_mid}")

        if lecture_sched or lec_zoom or "Lecture" in body:
            lecture_info = {
                "title": self.course_name or "Course Lecture",
                "schedule": lecture_sched or "See Syllabus Course Summary",
                "zoom_url": lec_zoom or None,
                "meeting_id": fmt_mid(lec_mid) if lec_mid else None
            }
        structured["lecture"] = lecture_info

        # 2. Dynamic Instructors Extraction
        instructors = []
        inst_m = re.search(r'Instructor(?:\s+Contact|\s+Information)?[:\s]+(.*?)(?=\n\s*(?:TA\s+Contact|Teaching\s+Assistant|Course\s+Summary)|\Z)', body, re.DOTALL | re.IGNORECASE)
        if inst_m:
            inst_text = inst_m.group(1)
            email_matches = list(re.finditer(r'([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})', inst_text))
            for i, em in enumerate(email_matches):
                email = em.group(1)
                start_pos = email_matches[i-1].end() if i > 0 else 0
                end_pos = email_matches[i+1].start() if i+1 < len(email_matches) else len(inst_text)
                segment = inst_text[start_pos:end_pos]

                # Name candidate: inspect non-empty lines before the email
                pre_email = inst_text[start_pos:em.start()]
                name_cand = ""
                for line in reversed([l.strip() for l in pre_email.splitlines() if l.strip()]):
                    cleaned_l = re.sub(r'^(?:Instructor|Name|Time|Link)[:\s]*', '', line, flags=re.IGNORECASE).strip().rstrip(':')
                    if cleaned_l and not re.match(r'^(?:Time|Link|\*|TBA)', cleaned_l, re.IGNORECASE):
                        nm = re.search(r'([A-Za-z\.\s]+):?$', cleaned_l)
                        name_cand = nm.group(1).strip() if nm else cleaned_l
                        break

                # Refine with title if mentioned in text or body
                if name_cand:
                    title_m = re.search(r'\b((?:Dr\.|Prof\.|Professor)\s+' + re.escape(name_cand) + r')\b', body, re.IGNORECASE)
                    if title_m:
                        name_cand = title_m.group(1).strip()
                    elif not name_cand.startswith(("Dr.", "Prof.")):
                        name_cand = f"Dr. {name_cand}"

                # Office hours
                oh = ""
                oh_m = re.search(r'((?:TBA|Tuesday|Thursday|Monday|Wednesday|Friday|Mon|Tue|Wed|Thu|Fri)[^\n\r]+(?:\n[^\n\r]+)?)', segment, re.IGNORECASE)
                if oh_m:
                    oh = re.sub(r'\s+', ' ', oh_m.group(1)).strip()

                # Note
                note = ""
                note_m = re.search(r'(\*[^\n\r]+)', segment)
                if note_m:
                    note = note_m.group(1).strip()

                # Meeting ID & Passcode
                mid_m = re.search(r'Meeting\s+ID:?[\s\xa0]*([\d\s]{9,13})', segment, re.IGNORECASE)
                mid_clean = re.sub(r'\D', '', mid_m.group(1)) if mid_m else ""
                pass_m = re.search(r'Passcode:?[\s\xa0]*(\w+)', segment, re.IGNORECASE)
                passcode = pass_m.group(1) if pass_m else ""

                zoom_url = zoom_urls.get(mid_clean, f"https://zoom.us/j/{mid_clean}" if mid_clean else "")

                inst_obj = {
                    "name": name_cand or "Course Instructor",
                    "role": "Course Instructor",
                    "email": email,
                    "office_hours": oh,
                    "zoom_url": zoom_url,
                    "meeting_id": fmt_mid(mid_clean) if mid_clean else ""
                }
                if passcode:
                    inst_obj["passcode"] = passcode
                if note:
                    inst_obj["note"] = note
                instructors.append(inst_obj)

        structured["instructors"] = instructors

        # 3. Dynamic Teaching Assistants Extraction
        tas = []
        ta_m = re.search(r'(?:TA|Teaching\s+Assistant)(?:\s+Contact|\s+Information)?[:\s]+(.*?)(?=\n\s*Course\s+Summary|\Z)', body, re.DOTALL | re.IGNORECASE)
        if ta_m:
            ta_text = ta_m.group(1)
            email_matches = list(re.finditer(r'([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})', ta_text))
            for i, em in enumerate(email_matches):
                email = em.group(1)
                prev_end = email_matches[i-1].end() if i > 0 else 0
                next_start = email_matches[i+1].start() if i+1 < len(email_matches) else len(ta_text)

                pre_text = ta_text[prev_end:em.start()]
                post_text = ta_text[em.end():next_start]

                # Section and Name from table row
                lines = [l.strip() for l in pre_text.splitlines() if l.strip()]
                last_line = lines[-1] if lines else ""
                parts = [p.strip() for p in re.split(r'\t+|\s{2,}', last_line) if p.strip()]

                sec = ""
                name = ""
                if len(parts) >= 3:
                    sec = parts[0]
                    name = f"{parts[2]} {parts[1]}"
                elif len(parts) == 2:
                    sec = parts[0]
                    name = parts[1]
                elif len(parts) == 1:
                    name = parts[0]

                if not sec:
                    sm = re.search(r'\b([A-H](?:\s*,\s*[A-H])?)\b', pre_text)
                    if sm:
                        sec = sm.group(1)

                mids = [re.sub(r'\D', '', m.group(1)) for m in re.finditer(r'Meeting\s+ID:?[\s\xa0]*([\d\s]{9,13})', post_text, re.IGNORECASE)]
                passes = [m.group(1) for m in re.finditer(r'Passcode:?[\s\xa0]*(\w+)', post_text, re.IGNORECASE)]

                disc_mid = mids[0] if len(mids) > 0 else ""
                oh_mid = mids[1] if len(mids) > 1 else ""
                disc_pass = passes[0] if len(passes) > 0 else ""
                oh_pass = passes[1] if len(passes) > 1 else ""

                ohm = re.search(r'((?:Monday|Tuesday|Wednesday|Thursday|Friday|Mon|Tue|Wed|Thu|Fri|Thur|Thursdays)[\s\w,:-]*(?:am|pm|PM|AM))', post_text, re.IGNORECASE)
                oh_text = re.sub(r'\s+', ' ', ohm.group(1)).strip() if ohm else ""

                tas.append({
                    "sections": sec,
                    "name": name,
                    "email": email,
                    "discussion_zoom_url": zoom_urls.get(disc_mid, f"https://zoom.us/j/{disc_mid}" if disc_mid else ""),
                    "discussion_meeting_id": fmt_mid(disc_mid) if disc_mid else "",
                    "discussion_passcode": disc_pass,
                    "office_hours": oh_text,
                    "office_hours_zoom_url": zoom_urls.get(oh_mid, f"https://zoom.us/j/{oh_mid}" if oh_mid else ""),
                    "office_hours_meeting_id": fmt_mid(oh_mid) if oh_mid else "",
                    "office_hours_passcode": oh_pass
                })

        structured["teaching_assistants"] = tas

        # 4. Schedule Items
        summary_idx = body.find("Course Summary:")
        schedule = []
        if summary_idx != -1:
            summary_text = body[summary_idx:]
            date_pat = re.compile(r'((?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+[A-Za-z]+\s+\d+,\s+\d{4})')
            parts = date_pat.split(summary_text)
            for i in range(1, len(parts), 2):
                d = parts[i].strip()
                content = parts[i+1].strip()
                blocks = re.split(r'\n\s*\n', content)
                for b in blocks:
                    b = b.strip()
                    if not b:
                        continue
                    is_assign = "Assignment" in b
                    cleaned = re.sub(r'(Calendar Event|Assignment)', '', b).strip()
                    lines = [l.strip() for l in cleaned.split('\t') if l.strip()]
                    title = lines[0] if len(lines) > 0 else cleaned
                    time_val = lines[1] if len(lines) > 1 else ""
                    title = title.replace('\n', ' ').strip()
                    time_val = time_val.replace('\n', ' ').strip()

                    matched_file = None
                    matched_path = None
                    for fn, fp in self.file_path_map.items():
                        fn_low = fn.lower()
                        t_low = title.lower()
                        if t_low in fn_low or (len(t_low) >= 8 and fn_low.startswith(t_low[:15])):
                            matched_file = fn
                            matched_path = fp
                            break

                    schedule.append({
                        "date": d,
                        "type": "Assignment" if is_assign else "Calendar Event",
                        "title": title,
                        "time": time_val,
                        "file_name": matched_file,
                        "file_path": matched_path
                    })
        structured["schedule"] = schedule

        self.syllabus["structured"] = structured

    def clean_announcements(self):
        """Cleans announcement text, removes screenreader artifacts, enriches author names, and formats URLs as Markdown.
        100% universal across any course: zero hardcoded topic IDs or author names.
        """
        for idx, ann in enumerate(self.announcements, 1):
            body = ann.get("body", "")
            title = ann.get("title", "")
            url = ann.get("url", "")

            # Extract topic ID
            m = re.search(r'/(?:discussion_topics|announcements)/(\d+)', url)
            topic_id = m.group(1) if m else str(idx)
            ann["id"] = topic_id

            # Clean and infer author generically
            raw_author = ann.get("author", "")
            clean_author = re.sub(r'(AUTHORTEACHER|TEACHER|TA|INSTRUCTOR)', '', raw_author).strip()
            if not clean_author or clean_author.lower() in ("course instructor", "instructor", "author", "teacher", "admin"):
                # Infer author generically from signoff or titles
                lines = [line.strip() for line in (body or "").splitlines() if line.strip()]
                found_author = ""
                signoff_triggers = (
                    "best", "thanks", "thank you", "sincerely", "warmly", "regards",
                    "best regards", "cheers", "all the best", "yours", "yours truly",
                    "with gratitude", "take care"
                )

                for i in range(len(lines) - 1, max(-1, len(lines) - 7), -1):
                    line = lines[i]
                    line_clean = line.rstrip(",.:!").lower()
                    if any(line_clean.startswith(trig) for trig in signoff_triggers):
                        if i + 1 < len(lines):
                            cand = lines[i + 1].strip()
                            if re.match(r'^(?:Dr\.|Prof\.|Professor\s+)?[A-Z][A-Za-z\.\s&,/-]+$', cand) and len(cand.split()) <= 6:
                                found_author = cand
                                break
                    # Single-line signoff e.g. "Best, Dr. Smith & Dr. Jones"
                    m_sign = re.match(r'^(?:Best|Thanks|Thank\s+you|Sincerely|Warmly|Regards|Cheers|Yours)[,\s]+((?:Dr\.|Prof\.|Professor\s+)?[A-Z][A-Za-z\.\s&,/-]+)$', line, re.IGNORECASE)
                    if m_sign:
                        cand = m_sign.group(1).strip()
                        if len(cand.split()) <= 6:
                            found_author = cand
                            break

                    m_title = re.match(r'^(?:Dr\.|Prof\.|Professor)\s+([A-Z][A-Za-z\.\s&,/-]+)$', line)
                    if m_title and len(line.split()) <= 6:
                        found_author = line
                        break

                    m_ta = re.match(r'^([A-Z][A-Za-z\s]+)\s*\((?:TA|Teaching\s+Assistant|Instructor|Professor)\)$', line)
                    if m_ta:
                        found_author = line
                        break

                if not found_author:
                    for line in lines[:3] + [title]:
                        m_top = re.search(r'\b((?:Dr\.|Prof\.|Professor)\s+[A-Z][A-Za-z\.\s&]+)', line)
                        if m_top:
                            cand = m_top.group(1).strip()
                            if len(cand.split()) <= 5:
                                found_author = cand
                                break

                clean_author = found_author or "Course Instructor"
            ann["author"] = clean_author

            # Universal DOM / screenreader / formatting cleaning
            cleaned_body = re.sub(r'Links to an external site\.?', '', body)
            cleaned_body = re.sub(r'\bActions\s+Preview\s+Download(?:\s+Alternative\s+formats)?\b', ' ', cleaned_body, flags=re.IGNORECASE)
            cleaned_body = re.sub(r'\bPreview\s+Download(?:\s+Alternative\s+formats)?\b', ' ', cleaned_body, flags=re.IGNORECASE)
            # Reconnect sentence fragments ONLY when broken by deleted button chrome (not across sentences or list items)
            cleaned_body = re.sub(r'(?<=[A-Za-z0-9,\'’])\n[ \t]+(from|to|in|of|on|at|with|as|\.)\b', r' \1', cleaned_body)
            # Universal attachment download deduplication (handles smart quotes, spaces, etc.)
            cleaned_body = re.sub(
                r'([A-Za-z0-9_\s.\'’\u2019\u2018-]+\.(?:pdf|docx?|pptx?|xlsx?|txt|zip|png|jpe?g))\s*(?:Actions\s+)?(?:Preview|Download)(?:\s+Alternative\s+formats)?(?:\s+\1)?',
                r'\1',
                cleaned_body,
                flags=re.IGNORECASE
            )
            # Remove isolated "Download filename.pdf" when on its own line or at the start of a block
            cleaned_body = re.sub(
                r'^[ \t]*(?:Actions\s+Preview\s+Download|Preview\s+Download|Download)\s+([A-Za-z0-9_\s.\'’\u2019\u2018-]+\.(?:pdf|docx?|pptx?|xlsx?|txt|zip|png|jpe?g))[ \t]*$',
                r'\1',
                cleaned_body,
                flags=re.IGNORECASE | re.MULTILINE
            )
            # Convert HTML anchor tags to Markdown
            cleaned_body = re.sub(r'<a\s+(?:[^>]*?\s+)?href=([\'"])(.*?)\1[^>]*>(.*?)</a>', r'[\3](\2)', cleaned_body, flags=re.IGNORECASE | re.DOTALL)
            # Convert bare URLs into Markdown links, carefully preserving trailing sentence punctuation
            def _linkify_bare_url(m):
                url = m.group(1)
                trailing = ""
                while url and url[-1] in ".,;:!?')\"":
                    trailing = url[-1] + trailing
                    url = url[:-1]
                return f"[{url}]({url}){trailing}"

            cleaned_body = re.sub(r'(?<!\]\()(?<!\[)(https?://[^\s\)\>]+)', _linkify_bare_url, cleaned_body)
            # Convert trailing non-breaking space (from Canvas <p> tags) + newline into clean paragraph breaks
            cleaned_body = re.sub(r'[\s\u00a0]*\u00a0\s*\n', '\n\n', cleaned_body)
            cleaned_body = cleaned_body.replace('\u00a0', ' ')
            # Ensure notes starting with * on a new line have distinct paragraph separation
            cleaned_body = re.sub(r'\n(?=\*[A-Za-z])', '\n\n', cleaned_body)
            # Normalize whitespace
            cleaned_body = re.sub(r'[ \t]+', ' ', cleaned_body)
            cleaned_body = re.sub(r'\n\s*\n\s*\n+', '\n\n', cleaned_body)
            # Collapse blank lines between sequential list items so loose lists don't break
            cleaned_body = re.sub(r'([ \t]*\d+\.[^\r\n]+)\r?\n\s*\r?\n(?=[ \t]*\d+\.)', r'\1\n', cleaned_body)
            cleaned_body = re.sub(r'([ \t]*[-*+][^\r\n]+)\r?\n\s*\r?\n(?=[ \t]*[-*+])', r'\1\n', cleaned_body)
            # Normalize signoffs (e.g., "Best,\nDr. Casas" without empty paragraph gap)
            cleaned_body = re.sub(r'\b(Best|Thanks|Thank\s+you|Sincerely|Warmly|Regards|Cheers)[,\s]*\r?\n+\s*([A-Z][A-Za-z\s&.-]+)$', r'\1,\n\2', cleaned_body, flags=re.MULTILINE | re.IGNORECASE)
            # Remove redundant parentheses from markdown links
            cleaned_body = re.sub(r'(\[[^\]]+\]\([^)]+\))\)+', r'\1', cleaned_body)

            ann["body"] = cleaned_body.strip()

            # Set distinct filename containing topic ID to prevent overwriting
            safe_title = re.sub(r'[\\/*?:"<>|]', '_', title).strip()
            ann_date = (ann.get("posted_at") or ann.get("date") or "2026-09-17")[:10]
            ann["file_name"] = f"{ann_date} - {topic_id} - {safe_title}.md"

    def link_announcements_to_files(self):
        """Cross-references announcement attachments with on-disk files and metadata dynamically.
        Pre-links filename mentions in announcement body into standard Markdown links.
        Zero course-specific hardcoding.
        """
        meta_path = os.path.join(self.output_dir, ".file_metadata.json")
        meta = {}
        if os.path.exists(meta_path):
            try:
                with open(meta_path, "r", encoding="utf-8") as f:
                    meta = json.load(f)
            except Exception:
                pass

        # Map page title -> file names
        files_by_page = {}
        for fname, item in meta.items():
            pt = item.get("page_title", "")
            if pt:
                files_by_page.setdefault(pt.lower().strip(), []).append(fname)

        # Helper for punctuation-insensitive normalized matching
        def norm_key(s: str) -> str:
            return re.sub(r'[\s_\'’\u2018\u2019\-]+', ' ', s).strip().lower()

        # Build normalized maps of on-disk files
        disk_files_normalized = {}
        disk_files_by_norm = {}
        disk_files_stems = {}
        disk_files_stems_norm = {}
        for fname, rpath in self.file_path_map.items():
            fname_low = fname.lower()
            disk_files_normalized[fname_low] = (fname, rpath)
            disk_files_by_norm[norm_key(fname)] = (fname, rpath)
            stem = re.sub(r'\.[a-zA-Z0-9]+$', '', fname).strip()
            if len(stem) >= 4:
                disk_files_stems[stem.lower()] = (fname, rpath)
                disk_files_stems_norm[norm_key(stem)] = (fname, rpath)

        for ann in self.announcements:
            title = ann.get("title", "")
            title_lower = title.lower().strip()
            body = ann.get("body", "")
            matched_files = {}  # fname -> (real_fname, rpath) or None

            # 1. Explicit attachments from scraper
            for att in ann.get("attachments", []):
                if isinstance(att, dict) and att.get("title"):
                    at_title = att["title"]
                    match = (disk_files_normalized.get(at_title.lower()) or 
                             disk_files_by_norm.get(norm_key(at_title)) or
                             disk_files_stems.get(at_title.lower()) or
                             disk_files_stems_norm.get(norm_key(at_title)))
                    if match:
                        matched_files[match[0]] = match
                    else:
                        matched_files[at_title] = None

            # 2. Metadata matching by page title
            if title_lower in files_by_page:
                candidates = files_by_page[title_lower]
                for cand in candidates:
                    cand_stem = re.sub(r'\.[a-zA-Z0-9]+$', '', cand).lower()
                    same_title_anns = [a for a in self.announcements if a.get("title", "").lower().strip() == title_lower]
                    if len(same_title_anns) > 1:
                        cand_tokens = set(re.findall(r'[a-zA-Z0-9]+', cand_stem)) - {'pdf', 'pptx', 'docx', 'xlsx', 'txt'}
                        body_tokens = set(re.findall(r'[a-zA-Z0-9]+', body.lower()))
                        if (cand_tokens & body_tokens) or (cand.lower() in body.lower()) or (cand_stem in body.lower()):
                            match = (disk_files_normalized.get(cand.lower()) or 
                                     disk_files_by_norm.get(norm_key(cand)) or
                                     disk_files_stems.get(cand_stem) or
                                     disk_files_stems_norm.get(norm_key(cand_stem)))
                            if match:
                                matched_files[match[0]] = match
                    else:
                        match = (disk_files_normalized.get(cand.lower()) or 
                                 disk_files_by_norm.get(norm_key(cand)) or
                                 disk_files_stems.get(cand_stem) or
                                 disk_files_stems_norm.get(norm_key(cand_stem)))
                        if match:
                            matched_files[match[0]] = match

            # 3. Resolve any existing markdown links pointing to course files or Canvas file endpoints
            def resolve_md_link(match):
                anchor = match.group(1)
                target = match.group(2)
                if target in self.file_path_map.values():
                    m = (disk_files_normalized.get(anchor.lower()) or 
                         disk_files_by_norm.get(norm_key(anchor)) or
                         disk_files_stems.get(anchor.lower()) or
                         disk_files_stems_norm.get(norm_key(anchor)))
                    if m:
                        matched_files[m[0]] = m
                    return match.group(0)

                m = (disk_files_normalized.get(anchor.lower()) or 
                     disk_files_by_norm.get(norm_key(anchor)) or
                     disk_files_stems.get(anchor.lower()) or
                     disk_files_stems_norm.get(norm_key(anchor)))

                if not m:
                    target_fname = target.split('?')[0].split('/')[-1]
                    if target_fname:
                        m = (disk_files_normalized.get(target_fname.lower()) or 
                             disk_files_by_norm.get(norm_key(target_fname)) or
                             disk_files_stems.get(target_fname.lower()) or
                             disk_files_stems_norm.get(norm_key(target_fname)))

                if m:
                    matched_files[m[0]] = m
                    return f"[{anchor}]({m[1]})"
                return match.group(0)

            body = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', resolve_md_link, body)

            # 4. Body text filename scanner & pre-linker
            # Skips existing markdown links or HTML tags to prevent nested brackets or corrupted URLs
            for cand_norm in sorted(disk_files_by_norm.keys(), key=len, reverse=True):
                if len(cand_norm) < 5:
                    continue
                parts = cand_norm.split()
                if not parts:
                    continue
                pat = r'[\s_\'’\u2018\u2019\-]+'.join(map(re.escape, parts))
                pattern = rf'(\[[^\]]*\]\([^)]*\)|<[^>]*>)|(?:\b({pat})\b)'
                real_fname, rpath = disk_files_by_norm[cand_norm]

                def repl_cand(m, rf=real_fname, rp=rpath):
                    if m.group(1):
                        return m.group(1)
                    matched_files[rf] = (rf, rp)
                    return f"[{m.group(2)}]({rp})"

                body = re.sub(pattern, repl_cand, body, flags=re.IGNORECASE)

            ann["body"] = body

            # Build resolved attachments list
            resolved_attachments = []
            for fname, match_info in matched_files.items():
                if match_info:
                    resolved_attachments.append({
                        "title": match_info[0],
                        "local_file": match_info[1],
                        "status": "available"
                    })
                else:
                    resolved_attachments.append({
                        "title": fname,
                        "local_file": None,
                        "status": "unavailable",
                        "status_note": "(link no longer available)"
                    })

            ann["attachments"] = resolved_attachments

    def link_gradescope_assignments(self):
        """Identifies Gradescope assignments and links prompt and submission files."""
        for assign in self.assignments:
            body = assign.get("body", "")
            title = assign.get("title", "")
            sub_type = assign.get("submission_types", "")
            is_gs = (
                assign.get("is_gradescope") or
                "gradescope" in body.lower() or
                "gradescope" in sub_type.lower() or
                "gradescope" in title.lower()
            )
            if is_gs:
                assign["is_gradescope"] = True
                if not assign.get("gradescope_url"):
                    assign["gradescope_url"] = "https://www.gradescope.com/"
                
            # Check for prompt or submission file in course files for all assignments
            safe_title = re.sub(r'[:/\\?*<>|]', '_', title).strip()
            candidates = [
                f"Assignment - {title}.txt",
                f"Assignment - {title}.pdf",
                f"Assignment - {safe_title}.txt",
                f"Assignment - {safe_title}.pdf",
                f"{title}.txt",
                f"{title}.pdf",
                f"{safe_title}.txt",
                f"{safe_title}.pdf",
                f"{title}_Submission.pdf",
                f"{title}_Graded_Copy.pdf"
            ]
            for c in candidates:
                for k, v in self.file_path_map.items():
                    if k.lower() == c.lower():
                        assign["local_file"] = v
                        break
                if assign.get("local_file"):
                    break

    def write_announcement_markdown_files(self, announcements_dir: str):
        """Writes out all announcements to disk as distinct, non-colliding Markdown files."""
        os.makedirs(announcements_dir, exist_ok=True)
        for ann in self.announcements:
            fname = ann.get("file_name")
            if not fname:
                date = (ann.get("posted_at") or ann.get("date") or "2026-09-17")[:10]
                tid = ann.get("id", "0")
                safe_t = re.sub(r'[\\/*?:"<>|]', '_', ann.get("title", "Announcement")).strip()
                fname = f"{date} - {tid} - {safe_t}.md"
                ann["file_name"] = fname

            filepath = os.path.join(announcements_dir, fname)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(f"# {ann.get('title', 'Announcement')}\n\n")
                f.write(f"- **Date Posted:** {ann.get('posted_at') or ann.get('date')}\n")
                f.write(f"- **Author:** {ann.get('author', 'Course Instructor')}\n")
                if ann.get("url"):
                    f.write(f"- **Canvas URL:** [{ann.get('url')}]({ann.get('url')})\n")
                f.write("\n---\n\n")
                f.write(ann.get("body", "*(No body text)*") + "\n")

                atts = ann.get("attachments", [])
                if atts:
                    f.write("\n\n### Attachments\n\n")
                    for att in atts:
                        t = att.get("title", "Attachment")
                        loc = att.get("local_file")
                        if loc:
                            f.write(f"- 📎 [{t}]({loc})\n")
                        else:
                            f.write(f"- 📎 {t} *(link no longer available)*\n")

    def synthesize_missing_modules(self):
        """Ensures all course materials on disk are accessible via modules.
        If a course has no modules (e.g. PSYCH 100B), synthesizes modules from physical folders.
        If a course has modules but orphaned files exist (e.g. CHEM 14D Discussion Slides or Reaction Maps),
        adds dedicated modules for them.
        """
        # 1. Clean up placeholder / syntax error modules
        self.modules = [
            m for m in self.modules 
            if m.get("id") != "{{ id }}" and not (m.get("title") == "General Materials" and len(m.get("items", [])) == 0)
        ]

        # Case A: Modules array is completely empty -> Synthesize from folder categories
        if len(self.modules) == 0 and self.file_path_map:
            folders_dict = {}
            for fname, rpath in sorted(self.file_path_map.items()):
                if is_synthetic_file(fname, rpath):
                    continue
                # Determine folder category
                parts = rpath.split("/")
                category = "Course Materials"
                if len(parts) > 1:
                    # e.g., "PSYCH 100B Lectures & Resources/PSYCH 100B Lecture Slides/..."
                    # Extract the meaningful category name
                    cat_candidate = parts[1] if len(parts) > 2 else parts[0]
                    category = clean_module_title(cat_candidate, self.course_name)
                folders_dict.setdefault(category, []).append({
                    "type": "generic",
                    "title": fname,
                    "local_file": rpath,
                    "indent": 0
                })

            # Sort items within each category using natural alphanumeric order
            for items in folders_dict.values():
                items.sort(key=lambda it: natural_sort_key(it.get("title", "")))

            # Sort categories by hierarchical tier and natural chronological order
            sorted_categories = sorted(
                folders_dict.items(),
                key=lambda pair: module_category_sort_key(pair[0])
            )

            for cat_idx, (cat_name, items) in enumerate(sorted_categories, start=1):
                self.modules.append({
                    "id": f"synth_{cat_idx}",
                    "title": cat_name,
                    "items": items
                })
            return

        # Case B: Modules exist, group any unlinked files on disk by their subfolder/category
        linked_files = set()
        for mod in self.modules:
            for item in mod.get("items", []):
                lf = item.get("local_file")
                if lf:
                    linked_files.add(lf)
                    linked_files.add(os.path.basename(lf))

        # Check for unlinked files clustering by common multi-word topic prefix (e.g. "Reaction Map")
        clustered_files = set()
        common_prefixes = {}
        for fname, rpath in sorted(self.file_path_map.items()):
            if is_synthetic_file(fname, rpath) or fname in linked_files or rpath in linked_files:
                continue
            words = re.findall(r'[A-Za-z0-9]+', fname)
            if len(words) >= 2 and words[0].lower() not in {"chapter", "ch", "week", "lecture", "assignment", "homework"}:
                prefix = f"{words[0]} {words[1]}"
                common_prefixes.setdefault(prefix.lower(), []).append((prefix, fname, rpath))

        for p_low, p_items in common_prefixes.items():
            if len(p_items) >= 2:
                disp_prefix = p_items[0][0]
                cluster_title = f"{disp_prefix}s & Guides" if not disp_prefix.endswith("s") else f"{disp_prefix} & Guides"
                cluster_mod_items = []
                for _, fn, rp in p_items:
                    cluster_mod_items.append({
                        "type": "generic",
                        "title": fn,
                        "local_file": rp,
                        "indent": 0
                    })
                    clustered_files.add(fn)
                    clustered_files.add(rp)
                self.modules.append({
                    "id": f"mod_cluster_{re.sub(r'[^a-zA-Z0-9_]', '_', p_low)}_{len(self.modules)+1}",
                    "title": cluster_title,
                    "items": cluster_mod_items
                })

        unlinked_by_folder = {}
        for fname, rpath in sorted(self.file_path_map.items()):
            if is_synthetic_file(fname, rpath) or fname in clustered_files or rpath in clustered_files:
                continue
            if fname not in linked_files and rpath not in linked_files:
                parts = rpath.split("/")
                if len(parts) > 1:
                    cat_candidate = parts[1] if len(parts) > 2 else parts[0]
                    category = clean_module_title(cat_candidate, self.course_name)
                else:
                    category = "Additional Materials"

                if "discussion slides" in category.lower() or "discussion presentation" in category.lower():
                    category = "Discussion Presentations & Slides"

                unlinked_by_folder.setdefault(category, []).append({
                    "type": "generic",
                    "title": fname,
                    "local_file": rpath,
                    "indent": 0
                })

        for cat_name, items in unlinked_by_folder.items():
            cat_lower = cat_name.lower()
            existing = next((m for m in self.modules if cat_lower in m.get("title", "").lower() or m.get("title", "").lower() in cat_lower), None)
            if existing:
                existing_files = {it.get("local_file") for it in existing.get("items", [])}
                for it in items:
                    if it["local_file"] not in existing_files:
                        existing.setdefault("items", []).append(it)
            else:
                self.modules.append({
                    "id": f"mod_synth_{re.sub(r'[^a-zA-Z0-9_]', '_', cat_name.lower())}_{len(self.modules)+1}",
                    "title": cat_name,
                    "items": items
                })

    def link_module_items_to_files(self):
        """Cross-references module items with the organized file paths on disk, resolving synonyms and key files accurately."""
        # 1. Prune placeholder / syntax error modules
        self.modules = [
            m for m in self.modules 
            if m.get("id") != "{{ id }}" and not (m.get("title") == "General Materials" and len(m.get("items", [])) == 0)
        ]

        normalized_map = {}
        for fname, rpath in self.file_path_map.items():
            base, _ = os.path.splitext(fname)
            clean_fname = re.sub(r'\s+', ' ', fname).strip().lower()
            clean_base = re.sub(r'\s+', ' ', base).strip().lower()
            normalized_map[clean_fname] = rpath
            normalized_map[clean_base] = rpath

        def is_key_file(s: str) -> bool:
            low = s.lower()
            return any(k in low for k in ["key", "solution", "soln", "answer key"])

        for mod in self.modules:
            for item in mod.get("items", []):
                title = item.get("title", "")
                title_clean = re.sub(r'\s+', ' ', title).strip().lower()
                base_clean = re.sub(r'\s+', ' ', os.path.splitext(title)[0]).strip().lower()

                # 1. Exact or normalized match
                if title_clean in normalized_map:
                    item["local_file"] = normalized_map[title_clean]
                    continue
                if base_clean in normalized_map:
                    item["local_file"] = normalized_map[base_clean]
                    continue

                # 2. Token overlap & substring match respecting key vs non-key
                is_key = is_key_file(title_clean)
                item_tokens = set(re.findall(r'[a-z0-9]+', title_clean)) - {
                    'the', 'a', 'an', 'and', 'or', 'for', 'of', 'in', 'on', 'at', 'to', 'with',
                    'pdf', 'pptx', 'docx', 'xlsx', 'txt', 'review', 'problems', 'exercises'
                }

                best_match = None
                best_score = 0

                for fname_clean, rpath in normalized_map.items():
                    target_is_key = is_key_file(fname_clean)
                    if is_key != target_is_key:
                        continue

                    # Substring match
                    if fname_clean in title_clean or title_clean in fname_clean or base_clean in fname_clean or fname_clean in base_clean:
                        best_match = rpath
                        break

                    # Token overlap match
                    fn_tokens = set(re.findall(r'[a-z0-9]+', fname_clean)) - {
                        'the', 'a', 'an', 'and', 'or', 'for', 'of', 'in', 'on', 'at', 'to', 'with',
                        'pdf', 'pptx', 'docx', 'xlsx', 'txt', 'review', 'problems', 'exercises'
                    }
                    if not item_tokens or not fn_tokens:
                        continue

                    overlap = len(item_tokens & fn_tokens)
                    score = overlap / max(len(item_tokens), len(fn_tokens))
                    if overlap >= 2 and score > best_score:
                        best_score = score
                        best_match = rpath

                if best_match:
                    item["local_file"] = best_match

    def to_dict(self) -> Dict[str, Any]:
        self.link_syllabus_files()
        self.clean_announcements()
        self.link_announcements_to_files()
        self.link_gradescope_assignments()
        self.synthesize_missing_modules()
        self.link_module_items_to_files()
        self.compile_timeline()
        res = {
            "course_name": self.course_name,
            "course_url": self.course_url,
            "scraped_at": self.scraped_at,
            "tabs": self.tabs,
            "modules": self.modules,
            "timeline": self.timeline,
            "assignments": self.assignments,
            "announcements": self.announcements,
            "discussions": self.discussions,
            "quizzes": self.quizzes,
            "syllabus": self.syllabus,
            "grades": self.grades,
            "media_recordings": self.media_recordings,
            "external_links": self.external_links,
            "file_path_map": self.file_path_map
        }
        if getattr(self, "is_synthesized", False):
            res["is_synthesized"] = True
            res["source"] = getattr(self, "source", "folder_backup")
        if getattr(self, "term", None):
            res["term"] = self.term
        return res

    def hydrate_from_canvas_api(self, cookies_path: str = None):
        """Enriches assignments and announcements with authoritative dates directly from Canvas REST API endpoints."""
        import requests
        from urllib.parse import urlparse

        if not cookies_path:
            p1 = os.path.join(self.output_dir, ".session_cookies.json")
            parent = os.path.dirname(self.output_dir.rstrip("/\\"))
            p2 = os.path.join(parent, ".session_cookies.json") if parent else ""
            if os.path.exists(p1):
                cookies_path = p1
            elif p2 and os.path.exists(p2):
                cookies_path = p2
            else:
                return

        if not os.path.exists(cookies_path):
            return

        parsed = urlparse(self.course_url)
        course_match = re.search(r'(/courses/\d+)', parsed.path)
        if not course_match:
            return
        course_id = course_match.group(1).replace("/courses/", "")

        try:
            with open(cookies_path, "r", encoding="utf-8") as f:
                cookies = json.load(f)
        except Exception:
            return

        session = requests.Session()
        session.headers.update({"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"})
        for c in cookies:
            session.cookies.set(c["name"], c["value"], domain=c.get("domain", ""), path=c.get("path", "/"))

        def clean_key(s: str) -> str:
            return re.sub(r'[^a-z0-9]', '', str(s).lower())

        api_base = f"{parsed.scheme}://{parsed.netloc}/api/v1/courses/{course_id}"

        # 1. Hydrate Announcements
        try:
            r_ann = session.get(f"{api_base}/discussion_topics?only_announcements=true&per_page=100", timeout=15)
            if r_ann.status_code == 200:
                ann_list = r_ann.json()
                ann_by_key = {clean_key(a.get("title", "")): a for a in ann_list}
                for bp_ann in self.announcements:
                    ck = clean_key(bp_ann.get("title", ""))
                    matched = ann_by_key.get(ck)
                    if not matched:
                        for k, v in ann_by_key.items():
                            if k in ck or ck in k:
                                matched = v
                                break
                    if matched:
                        real_date = matched.get("posted_at") or matched.get("created_at")
                        if real_date:
                            bp_ann["posted_at"] = real_date
                            bp_ann["date"] = real_date[:10]
        except Exception as e:
            print(f"   ℹ️ Notice during announcements API hydration: {e}")

        # 2. Hydrate Assignments
        try:
            r_assign = session.get(f"{api_base}/assignments?per_page=100", timeout=15)
            if r_assign.status_code == 200:
                assign_list = r_assign.json()
                assign_by_key = {clean_key(a.get("name", "")): a for a in assign_list}
                for bp_assign in self.assignments:
                    ck = clean_key(bp_assign.get("title", ""))
                    matched = assign_by_key.get(ck)
                    if not matched:
                        for k, v in assign_by_key.items():
                            if k in ck or ck in k:
                                matched = v
                                break
                    if matched:
                        assigned_date = matched.get("unlock_at") or matched.get("created_at")
                        due_date = matched.get("due_at")
                        lock_date = matched.get("lock_at")
                        pts = matched.get("points_possible")

                        if assigned_date:
                            bp_assign["available_from"] = assigned_date
                            bp_assign["date_assigned"] = assigned_date[:10]
                            bp_assign["created_at"] = matched.get("created_at")
                        if due_date:
                            bp_assign["due_date"] = due_date
                        if lock_date:
                            bp_assign["until"] = lock_date
                        if pts is not None:
                            bp_assign["points"] = pts
        except Exception as e:
            print(f"   ℹ️ Notice during assignments API hydration: {e}")

    def generate_markdown_timeline(self) -> str:
        """Generates a human-readable Markdown timeline of assignments, posts, and milestones."""
        lines = [
            f"# {self.course_name} Assignments, Posts & Milestones Timeline",
            f"**Generated**: {time.strftime('%B %d, %Y')}",
            f"**Total Tracked Milestones**: {len(self.timeline)}\n",
            "| Date Assigned / Posted | Due Date | Type | Title | Points | Status | Linked Resource |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |"
        ]
        type_icons = {
            "assignment": "📝 Assignment",
            "announcement": "📢 Announcement",
            "quiz": "❓ Quiz",
            "discussion": "💬 Discussion"
        }
        for ev in self.timeline:
            assigned = format_datetime_for_display(ev.get("date_assigned"))
            due = format_datetime_for_display(ev.get("date_due"))
            t_icon = type_icons.get(ev.get("type"), str(ev.get("type")).title())
            title = ev.get("title", "Untitled")
            pts = f"{ev.get('points')} pts" if ev.get("points") else "—"
            status = str(ev.get("submission_status", "Active")).title()
            local_file = ev.get("local_file")
            file_link = f"[{os.path.basename(local_file)}]({local_file})" if local_file else "—"
            lines.append(f"| {assigned} | {due} | {t_icon} | {title} | {pts} | {status} | {file_link} |")
        return "\n".join(lines) + "\n"

    def save(self, target_dir: str, *, course_root=None):
        """[Codex] Publish only within a caller-supplied trusted course root.

        Without an explicit root the target itself is the boundary. Blueprint
        metadata and the target's parent never grant permission to write elsewhere.
        """
        validate_component(self.course_name)
        root = Path(contained_path(course_root or target_dir))
        target = Path(contained_path(target_dir))
        target.relative_to(root)
        md_name = f"{self.course_name} Assignments_and_Milestones_Timeline.md"
        destinations = [(target / "canvas_course.json", "json"), (target / md_name, "text")]
        if target != root:
            destinations.append((root / "canvas_course.json", "json"))
        work = root / f"{self.course_name} Work"
        if work.exists() or work.is_symlink():
            contained_path(root, work.relative_to(root))
            if work.is_dir():
                destinations.append((work / md_name, "text"))
        if os.name == 'nt':
            # Windows lacks directory-relative open/replace. Validate every
            # destination first, then stage files in each destination folder.
            for destination, _ in destinations:
                contained_path(root, destination.relative_to(root))
                if destination.exists() and not destination.is_file():
                    raise ValueError('Blueprint destinations must be regular files')
            try:
                self.hydrate_from_canvas_api()
            except Exception:
                pass
            self.link_module_items_to_files()
            self.compile_timeline()
            payloads = {"json": json.dumps(self.to_dict(), indent=2),
                        "text": self.generate_markdown_timeline()}
            for destination, kind in destinations:
                _atomic_blueprint_write_windows(root, destination, payloads[kind])
            print("📋 Canvas blueprint and timeline saved within the course directory.")
            return
        # Pin every destination directory before preparing data or changing files.
        with ExitStack() as stack:
            handles = []
            for destination, kind in destinations:
                fd = _open_blueprint_directory(root, destination.parent)
                stack.callback(os.close, fd)
                _check_blueprint_target(fd, destination.name)
                handles.append((fd, destination.name, kind))
            try:
                self.hydrate_from_canvas_api()
            except Exception:
                pass
            self.link_module_items_to_files()
            self.compile_timeline()
            payloads = {"json": json.dumps(self.to_dict(), indent=2),
                        "text": self.generate_markdown_timeline()}
            for fd, name, kind in handles:
                _atomic_blueprint_write(fd, name, payloads[kind])
        print("📋 Canvas blueprint and timeline saved within the course directory.")


def _open_blueprint_directory(root, directory):
    """[Codex] Open all directory components without following symlinks."""
    root = Path(contained_path(root))
    relative = Path(directory).relative_to(root)
    fd = os.open(root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    try:
        for part in relative.parts:
            validate_component(part)
            child = os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=fd)
            os.close(fd)
            fd = child
        return fd
    except BaseException:
        os.close(fd)
        raise


def _check_blueprint_target(directory_fd, name):
    validate_component(name)
    try:
        info = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
    except FileNotFoundError:
        return
    if not stat.S_ISREG(info.st_mode):
        raise ValueError("Blueprint destinations must be regular files, not symbolic links")


def _atomic_blueprint_write(directory_fd, name, content):
    _check_blueprint_target(directory_fd, name)
    temporary = ".blueprint-" + secrets.token_hex(16)
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                 0o600, dir_fd=directory_fd)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        _check_blueprint_target(directory_fd, name)
        os.replace(temporary, name, src_dir_fd=directory_fd, dst_dir_fd=directory_fd)
    finally:
        try:
            os.unlink(temporary, dir_fd=directory_fd)
        except FileNotFoundError:
            pass


def _atomic_blueprint_write_windows(root, destination, content):
    """Best available contained atomic replacement without POSIX dir fds."""
    import tempfile
    contained_path(root, destination.relative_to(root))
    if destination.exists() and not destination.is_file():
        raise ValueError('Blueprint destinations must be regular files')
    fd, temporary = tempfile.mkstemp(prefix='.blueprint-', dir=destination.parent)
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        contained_path(root, destination.relative_to(root))
        os.replace(temporary, destination)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


ACADEMIC_CATEGORY_WORDS = {
    'week', 'wk', 'module', 'mod', 'unit', 'chapter', 'ch', 'project', 'lecture',
    'lectures', 'lec', 'discussion', 'disc', 'lab', 'labs', 'homework', 'hw',
    'assignment', 'assignments', 'part', 'section', 'session', 'topic', 'quiz',
    'quizzes', 'exam', 'exams', 'midterm', 'final', 'paper', 'papers', 'essay',
    'essays', 'reading', 'readings', 'syllabus', 'course', 'textbook', 'textbooks'
}


def natural_sort_key(s: str) -> list:
    """Natural alphanumeric sort key for human-readable ordering (e.g. Week 1 before Week 10)."""
    return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', str(s))]


def clean_module_title(title: str, course_name: str = "") -> str:
    """
    Universal cleanup of redundant course codes and prefixes from folder categories.
    E.g. 'ISLM ST M20 Readings' -> 'Readings', 'HIST 8A Lectures' -> 'Lectures',
    'PSYCH 100B Lecture Slides' -> 'Lecture Slides', 'Week 5' -> 'Week 5'.
    Zero-hardcoding regex heuristics.
    """
    cleaned = str(title).strip()
    first_word = cleaned.split()[0].lower() if cleaned.split() else ''
    first_word_clean = re.sub(r'[^a-z]', '', first_word)

    # If the title starts with an academic category word (e.g. Week 1, Project 1, Lab 2), never strip it
    if first_word_clean in ACADEMIC_CATEGORY_WORDS:
        return cleaned

    if course_name:
        c_esc = re.escape(course_name.strip())
        after_c = re.sub(r'^(?:' + c_esc + r')\s*[-:_/]?\s*', '', cleaned, flags=re.IGNORECASE).strip()
        if after_c and after_c != cleaned:
            return after_c

    # Generic academic course code regex with strict word boundary on course number/code
    # e.g. HIST 8A, CS 31, MATH 33B, ISLM ST M20, ISLAM ST M20
    m = re.match(
        r'^([A-Za-z\s&]{2,20}?\b(?:[A-Za-z]{1,3}\s*)?\d{1,4}[A-Za-z]{0,3}\b)\s*[-:_/]?\s*(.+)$',
        cleaned
    )
    if m:
        prefix = m.group(1).strip().lower()
        remainder = m.group(2).strip()
        p_first = re.sub(r'[^a-z]', '', prefix.split()[0]) if prefix.split() else ''
        if p_first not in ACADEMIC_CATEGORY_WORDS and remainder:
            return remainder

    return cleaned


def module_category_sort_key(title: str) -> tuple:
    """
    Universal hierarchical and natural chronological sort key for course modules.

    Hierarchy:
    Tier 1: Syllabus / Getting Started / Course Overview / Policies
    Tier 2: Primary Study Materials (Lectures, Readings, Textbooks, Resources)
    Tier 3: Chronological Units (Weeks, Modules, Units, Topics, Chapters, Sessions)
    Tier 4: Discussions, Labs & Recitations
    Tier 5: Student Work, Assignments, Homework, Problem Sets & Essays
    Tier 6: Exams, Quizzes & Assessments
    Tier 7: Everything else (Alphabetical with natural number sort)
    """
    norm = str(title).strip().lower()

    # Tier 1: Syllabus / Getting Started / Course Overview / Policies
    if any(k in norm for k in ('syllabus', 'course info', 'overview', 'policies', 'general info', 'welcome', 'start here', 'critical doc')):
        return (1, 0, natural_sort_key(norm))

    # Tier 2: Primary Study Materials (Lectures, Readings, Textbooks, Resources)
    # Check if title is a single lecture unit like 'Lecture 1' or 'Lec 02'
    single_lec = re.search(r'\b(?:lecture|lec|session)\s*(\d+)\b', norm)
    if single_lec:
        return (3, int(single_lec.group(1)), natural_sort_key(norm))
    if 'lecture' in norm or 'slide' in norm or 'deck' in norm:
        return (2, 1, natural_sort_key(norm))
    if 'reading' in norm or 'textbook' in norm or 'book' in norm:
        return (2, 2, natural_sort_key(norm))
    if any(k in norm for k in ('handout', 'resource', 'reference', 'guide', 'note', 'material', 'outline')):
        return (2, 3, natural_sort_key(norm))

    # Tier 3: Chronological / Time-Based (Weeks, Modules, Units, Topics, Chapters)
    week_m = re.search(r'\b(?:week|wk|w)\s*(\d+)\b', norm)
    if week_m:
        return (3, int(week_m.group(1)), natural_sort_key(norm))
    mod_m = re.search(r'\b(?:module|mod|unit|topic|chapter|ch|part)\s*(\d+)\b', norm)
    if mod_m:
        return (3, int(mod_m.group(1)), natural_sort_key(norm))

    # Tier 4: Discussions, Labs & Recitations
    if 'discussion' in norm or 'disc' in norm:
        num = re.search(r'\d+', norm)
        return (4, int(num.group(0)) if num else 0, natural_sort_key(norm))
    if 'lab' in norm:
        num = re.search(r'\d+', norm)
        return (4, 50 + (int(num.group(0)) if num else 0), natural_sort_key(norm))
    if any(k in norm for k in ('recitation', 'workshop', 'seminar', 'pss')):
        num = re.search(r'\d+', norm)
        return (4, 100 + (int(num.group(0)) if num else 0), natural_sort_key(norm))

    # Tier 5: Student Work, Assignments, Homework, Problem Sets & Essays
    if any(k in norm for k in ('homework', 'hw', 'assignment', 'pset', 'problem set', 'essay', 'paper', 'project', 'capstone', 'memo', 'writing', 'work')):
        num = re.search(r'\d+', norm)
        return (5, int(num.group(0)) if num else 0, natural_sort_key(norm))

    # Tier 6: Exams, Quizzes & Assessments
    if any(k in norm for k in ('quiz', 'exam', 'midterm', 'test', 'final', 'review')):
        sub = 1 if 'quiz' in norm else (2 if 'midterm' in norm else (3 if 'final' in norm else 4))
        num = re.search(r'\d+', norm)
        return (6, sub * 100 + (int(num.group(0)) if num else 0), natural_sort_key(norm))

    # Tier 7: Everything else
    num = re.search(r'\d+', norm)
    return (7, int(num.group(0)) if num else 0, natural_sort_key(norm))


def infer_course_name_from_folder(folder_name: str) -> str:
    """
    Infers a clean course name from a folder name (e.g. 'CHEM 14D Backup' -> 'CHEM 14D',
    'Winter 2024 - CS 32' -> 'CS 32', 'Econ 101 Materials' -> 'ECON 101').
    Zero-hardcoding regex heuristics.
    """
    raw = folder_name.strip()
    # Strip backup, notes, materials, files, archive suffixes
    cleaned = re.sub(
        r'(?i)\b(backup|files|materials|lectures\s*&\s*resources|work|archive|folder|downloads|notes|resources)\b',
        '',
        raw
    ).strip()
    # Strip term prefixes/suffixes from the name (e.g. "Winter 2024 - ", " - Fall 2023")
    cleaned = re.sub(
        r'(?i)\b(Winter|Spring|Summer|Fall|Autumn)(?:\s+(?:Quarter|Semester|Term|Session(?:\s+[A-Za-z0-9]+)?))?\s+\d{4}\b',
        '',
        cleaned
    ).strip()
    cleaned = re.sub(
        r'(?i)\b\d{4}\s+(Winter|Spring|Summer|Fall|Autumn)\b',
        '',
        cleaned
    ).strip()
    cleaned = re.sub(r'^[_\-\s\.:;]+|[_\-\s\.:;]+$', '', cleaned)

    # Check for course code pattern: 2-8 letters followed by 1-4 numbers and optional letters
    # e.g. "CHEM 14D", "CS 31", "MATH 33A", "COM SCI 180", "PHYSICS 5C", "ECON 101", "HIST 1B"
    m = re.search(r'\b([A-Za-z\s&]{2,12}\s*\d{1,4}[A-Za-z]{0,3})\b', cleaned)
    if m:
        code = m.group(1).strip()
        parts = code.rsplit(None, 1)
        if len(parts) == 2:
            return f"{parts[0].upper()} {parts[1].upper()}"
        return code.upper()

    return cleaned or raw


def synthesize_course_blueprint(
    course_dir: Any,
    course_name: Optional[str] = None,
    term: Optional[str] = None,
    save: bool = True
) -> "CourseBlueprint":
    """
    Scans any unindexed folder (backed up without the Canvas scraper) and synthesizes
    a complete CourseBlueprint (canvas_course.json) and milestone timeline markdown.
    
    - Infers course name and academic term
    - Recursively maps all course files into file_path_map
    - Synthesizes LMS modules from existing subfolders on disk
    - Detects syllabus PDF / documents and extracts course overview
    - Identifies assignments, homework, and exams for the Quarter Timeline
    - Persists canvas_course.json non-destructively in the course folder
    """
    from pathlib import Path
    path_obj = Path(contained_path(course_dir))
    if not path_obj.exists() or not path_obj.is_dir():
        raise ValueError(f"Directory does not exist or is not a directory: {course_dir}")

    resolved_name = course_name or infer_course_name_from_folder(path_obj.name)
    bp = CourseBlueprint(
        course_name=resolved_name,
        course_url="",
        output_dir=str(path_obj)
    )
    bp.is_synthesized = True
    bp.source = "folder_backup"

    # Standard LMS tabs
    bp.tabs = [
        {"id": "modules", "label": "Modules", "url": "", "type": "modules"},
        {"id": "syllabus", "label": "Syllabus", "url": "", "type": "syllabus"},
        {"id": "assignments", "label": "Assignments", "url": "", "type": "assignments"},
        {"id": "folders", "label": "Desktop Folders", "url": "", "type": "folders"},
        {"id": "timeline", "label": "Quarter Timeline", "url": "", "type": "timeline"},
    ]

    # Scan directory to populate file_path_map
    bp.scan_course_directory(str(path_obj))

    # Detect term if not provided
    if term:
        bp.term = term
    else:
        # Check folder name first
        term_cand = None
        term_m1 = re.search(r'\b(Winter|Spring|Summer|Fall|Autumn)(?:\s+(?:Quarter|Semester|Term))?\s+(\d{4})\b', path_obj.name, re.IGNORECASE) or \
                  re.search(r'\b(Winter|Spring|Summer|Fall|Autumn)(?:\s+(?:Quarter|Semester|Term))?\s+(\d{4})\b', path_obj.parent.name, re.IGNORECASE)
        if term_m1:
            season = term_m1.group(1).capitalize()
            if season.lower() == 'autumn':
                season = 'Fall'
            term_cand = f"{season} {term_m1.group(2)}"
        if not term_cand and bp.syllabus.get("pdf_file"):
            syl_name = bp.syllabus["pdf_file"]
            term_m2 = re.search(r'\b(Winter|Spring|Summer|Fall|Autumn)(?:\s+(?:Quarter|Semester|Term))?\s+(\d{4})\b', syl_name, re.IGNORECASE)
            if term_m2:
                season = term_m2.group(1).capitalize()
                if season.lower() == 'autumn':
                    season = 'Fall'
                term_cand = f"{season} {term_m2.group(2)}"
        if term_cand:
            bp.term = term_cand

    # Synthesize assignments from file paths if none exist
    if not bp.assignments and bp.file_path_map:
        assign_idx = 1
        assign_pat = re.compile(
            r'(?i)\b(hw|homework|assignment|pset|problem\s*set|project|lab|quiz|exam|midterm|final)\s*([0-9A-Za-z_-]*)'
        )
        for fname, rpath in sorted(bp.file_path_map.items()):
            parts = [p.lower() for p in rpath.split("/")[:-1]]
            is_assign_sub = any(
                p in ("homework", "assignments", "problem sets", "psets", "hw", "labs", "projects", "quizzes", "exams", "midterms", "finals")
                for p in parts
            )
            m = assign_pat.search(fname)
            if is_assign_sub or m:
                r_low = rpath.lower()
                group = "Assignments"
                if any(x in r_low for x in ("exam", "midterm", "final")):
                    group = "Exams"
                elif "quiz" in r_low:
                    group = "Quizzes"
                elif "lab" in r_low:
                    group = "Labs"
                elif "project" in r_low:
                    group = "Projects"

                file_abs = path_obj / rpath
                mtime_iso = None
                try:
                    mtime = os.path.getmtime(file_abs)
                    mtime_iso = datetime.fromtimestamp(mtime).isoformat()
                except Exception:
                    pass

                title = re.sub(r'\.[a-zA-Z0-9]+$', '', fname).replace('_', ' ').replace('-', ' ').strip()
                bp.assignments.append({
                    "id": f"synth_assign_{assign_idx}",
                    "title": title,
                    "due_date": mtime_iso,
                    "available_from": mtime_iso,
                    "points": None,
                    "group": group,
                    "submission_status": "archived",
                    "local_file": rpath,
                    "url": ""
                })
                assign_idx += 1

    # Re-compile modules and timeline
    bp.synthesize_missing_modules()
    bp.link_module_items_to_files()
    bp.compile_timeline()

    if save:
        validate_component(bp.course_name)
        destinations = [path_obj / "canvas_course.json"]
        for sub in path_obj.iterdir():
            if sub.is_dir() and not sub.is_symlink() and any(
                    word in sub.name.lower() for word in ("lecture", "resource", "material")):
                destinations.append(sub / "canvas_course.json")
                break
        destinations.append(path_obj / f"{bp.course_name} Assignments_and_Milestones_Timeline.md")
        with ExitStack() as stack:
            handles = []
            for dest in destinations:
                fd = _open_blueprint_directory(path_obj, dest.parent)
                stack.callback(os.close, fd)
                _check_blueprint_target(fd, dest.name)
                handles.append((fd, dest.name))
            for fd, name in handles:
                payload = json.dumps(bp.to_dict(), indent=2) if name == "canvas_course.json" else bp.generate_markdown_timeline()
                _atomic_blueprint_write(fd, name, payload)

    return bp
